import "app/globals.css";
import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import localFont from "next/font/local";
import HeaderBar from "app/components/headerBar";
import Footer from "app/components/footer";

const courrierPrime = Courier_Prime({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-courrier-prime",
});
const SixtyFour = localFont({
  src: "../fonts/Sixtyfour-Regular-Variable.ttf",
  weight: "400",
  variable: "--font-sixty-four",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${courrierPrime.variable} ${SixtyFour.variable}`}
    >
      <body className={`${courrierPrime.className}`}>
        <HeaderBar />
        <div className="container mb-5 mt-10 space-y-20">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
