name: Publish

on:
  workflow_dispatch:

  push:
    branches: [main]

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: '18.20'
          cache: yarn

      - name: Fetch dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build website
        run: |
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.OPS_TOKEN }}
          publish_dir: ./out
          cname: axone.xyz
